#server
server:
  port: 8001
  context-path: /framework
#------------------------------------------------------------
#spring
spring:
  druid:
    #配置druid连接池
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@localhost:1521/orcl
      username: test
      password: Test123
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#------------------------------------------------------------
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
    jackson:
      serialization:
        indent_output: true
#------------------------------------------------------------
#freemarker
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
#------------------------------------------------------------
#themeleaf
  themeleaf:
    prefix: /WEB-INF/views
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
#------------------------------------------------------------
#mybatis-plus
mybatis-plus:
  global-config:
    id-type: 3
    field-strategy: 0
    db-column-underline: false
    refresh-mapper: true
    capital-mode: false
    logic-delete-value: 0
    logic-not-delete-value: 1
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.syfri.userservice.entity
  executor-type: simple
  configuration:
    cache-enabled: false
    lazy-loading-enabled: false
    jdbc-type-for-null: other
    local-cache-scope: session
    lazy-load-trigger-methods: equals,clone,hashCode,toString
#------------------------------------------------------------
#pagehelper分页插件设置
pagehelper:
  helper-dialect: oracle
  reasonable: true
  support-methods-arguments: true
  row-bounds-with-count: true
  auto-dialect: true
#------------------------------------------------------------
#dubbo
#dubbo:
#  application:
#    name: user-provider
#  registry:
#    protocol: zookeeper
#    address: 127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183
#  protocol:
#    name: dubbo
#    port: 20880
#------------------------------------------------------------
#dubbo.provider
dubbo:
  provider:
    applicationName: user-provider
    registryProtocol: zookeeper
    registryAddress: 127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183
    protocolName: dubbo
    protocolPort: 20880
    monitorProtocol: registry
    serviceTimeout: 0
    serviceRetries: 6000
    annotationPackage: com.syfri.userservice.service
#------------------------------------------------------------